branches:
  only:
    - docs

install:
  - gem install asciidoctor
  - sudo pip install Pygments
  - rm -rf public || exit 0

script:
  - source ./hack/init.sh
  - ./bin/hugo
  - cd public
  - touch .nojekyll
  - echo "redhatgov.io" > CNAME
  - ls -lah

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: docs

notifications:
  slack: redhat:9meDz4fnYsXtr3krfjmSXADX
