---
title: "Exercise 1.1 - Managing Updates Using the Web Console"
workshops: rhel_8
workshop_weight: 11
layout: lab
---

:icons: font
:imagesdir: /workshops/rhel_8/images
:figure-caption!:
:become_url: http://docs.ansible.com/ansible/become.html
:dir_url: http://docs.ansible.com/ansible/playbooks_best_practices.html
:package_url: http://docs.ansible.com/ansible/package_module.html
:service_url: http://docs.ansible.com/ansible/service_module.html
:yaml_url: http://docs.ansible.com/ansible/YAMLSyntax.html


= Exercise 1.1 - Managing Updates Using the Web Console

== Exercise Description

Now that you've toured the web console, lets work through updating the system. 

== Section 1: Basic Updating

As you did in the previous section, navigate to the `Software Updates` section of the Web Console, by licking on the `Software Updates` link, in the left-hand menu. There will then be a brief interval where `Refreshing package information` will appear, along with a progress bar. Once that completes, you can proceed with the exercise.

=== Step 1: Update Some Packages
Create a directory called *apache_basic* in your home directory and change directories to it.

[source,bash]
----
mkdir ~/apache_basic
cd ~/apache_basic
----

=== Step 2: Open the apache install
Use `vi` or `vim` to open a file called `install_apache.yml`




== Section 2: Defining Your play

Now that you are editing `install_apache.yml`, let's begin by defining the play. Then, we'll take some time to understand what each line accomplishes.



[source,bash]
----
---
- hosts: web
  name: Install the apache web service
  become: yes
----



- `---` Defines the beginning of YAML
- `hosts: web` Defines the host group in your inventory on which this play will run against.
- `name: Install the apache web service` This describes our play.
- `become: yes` Enables user privilege escalation.  The default is sudo, but su, pbrun, and link:{become_url}[several others] are also supported.


== Section 3: Adding tasks to your play

Now that we've defined your play, let's add some tasks to get some things done.  Align (vertically) the *t* in `task` with the *b* `become`.  +

Yes, it does actually matter.  In fact, you should make sure all of your playbook statements are aligned, as shown here. +

If you want to see the entire playbook for reference, skip to the bottom of this exercise.


[source,bash]
----
tasks:
 - name: install apache
   package:
     name: httpd
     state: present

 - name: start httpd
   service:
     name: httpd
     state: started
----



- `tasks:` This denotes that one or more tasks are about to be defined
- `- name:` Each task requires a name, which will print to standard output when you run your playbook.
Therefore, give your tasks a name that is short, sweet, and to the point




[source,text]
----
package:
  name: httpd
  state: present
----


- These three lines are calling the Ansible module *package* to install httpd.
link:{package_url}[Click here] to see all options for the package module.



[source,text]
----
service:
  name: httpd
  state: started
----



- The next few lines are using the ansible module *service* to start the httpd service.  The service module
is the preferred way of controlling services on remote hosts.  link:{service_url}[Click here] to learn more
about the *service* module.



== Section 4: Saving your playbook

Now that you've completed writing your playbook, it would be a shame not to keep it for later use.

Use the `write/quit` method in `vi` or `vim` to save your playbook, i.e. `Esc :wq!`


And that should do it.  You should now have a fully written playbook called `install_apache.yml`.
You are ready to automate!

[NOTE]
Ansible (well, YAML really) can be a bit particular about formatting, especially around indentation/spacing.  When you all get back to the office,
read up on this link:{yaml_url}[YAML Syntax] a bit more and it will save you some headaches later.  In the meantime, your completed playbook should look
like this.  Take note of the spacing and alignment.

[source,bash]
----
---
- hosts: web
  name: Install the apache web service
  become: yes

  tasks:
    - name: install apache
      package:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started
----

{{< importPartial "footer/footer.html" >}}
