---
title: OpenShift Security Workshop
menu:
  main:
    parent: workshops
    pre: fa fa-shield
---

:badges:
:icons: font
:imagesdir: /workshops/security_openshift/images
:source-highlighter: highlight.js
:source-language: yaml

= OpenShift Security Workshop

== Description

Learn about secrets and how to Secure  your microservices and containers by using and extending Linux scanning features, SCC,  Seccomp and the security API.

== Who should attend

- Anyone who has had any exposure to Containers
- Architects
- Developers
- Technical leads
- Operations Engineers

== What you will learn

- SELinux
- Openshift deployment
- SCC
- Seccomp
- Security API

== Overview

Today is meant for anyone who has any exposure to Containers, whether you have used them or not. We are going to start with a short overview (yes, slideware) and then we’ll get into the lab as soon as possible. That is where we will spend most of our time.

=== Your Responsibilities

Have a discussion. This will be boring if it’s just us up here talking for over 4 hours.
Participate. We are going to cut you loose with Containers here in just a little while. Have questions. Have opinions.
Hopefully you have your laptop with you. If not, please ask an instructor for a laptop.
Agenda

== Labs

{{< labs security_openshift >}}


{{% alert success %}}
Special Thanks to:

- Dan Walsh
- Bob Kozdemba
- Brent Baude
- Adrian Mouat
{{% /alert %}} 


