---
title: Container Security Workshop
menu:
  main:
    parent: workshops
    pre: fa fa-lock
---

:badges:
:icons: font
:imagesdir: /workshops/security_containers/images
:source-highlighter: highlight.js
:source-language: yaml

= Container Security Workshop

== Description

Learn how to scan, secure  and leverage properties in  the Linux kernel  like seccomp, namespaces, ccgroups to secure your docker containers.

== Who should attend

- People familiar with containers that have had Containers 101
- Architects
- Developers
- Technical leads
- Operations Engineers

== What you will learn

- Cockpit
- CGroups
- Namespaces
- Seccomp
- SELinux

== Overview

Today is meant for anyone who has any exposure to containers, whether you have used them or not. We are going to start with a short overview (yes, slideware) and then we’ll get into the lab as soon as possible. That is where we will spend most of our time.

== Your Responsibilities

Have a discussion. This will be boring if it’s just us up here talking for over 4 hours.
Participate. We are going to cut you loose with containers here in just a little while. Have questions. Have opinions.
Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into containers but you can make a new friend!
Agenda

== Labs

{{< labs security_containers >}}



{{% alert success %}}
Special Thanks to:

- Dan Walsh
- Bob Kozdemba
- Brent Baude
- Adrian Mouat
{{% /alert %}}

{{< importPartial "footer/footer.html" >}}
