---
title: "Exercise 1.5 - Namespaces"
workshops: security_containers
workshop_weight: 70
layout: lab
---

:icons: font
:imagesdir: /workshops/security_containers/images

= Exercise 1.5 - Namespaces

== Pid Namespace

PID namespaces allow processes in different containers to have the same PID, so each container can have its own init (PID1) process that manages various system initialization tasks as well as containers life cycle. Also, each container has its unique /proc directory. Note that from within the container you can monitor only processes running inside this container. In other words, the container is only aware of its native processes and can not "see" the processes running in different parts of the system. On the other hand, the host operating system is aware of processes running inside of the container, but assigns them different PID numbers.

Let's launch a container in it's own namespace and see what process it can see from inside the container.

[source, bash]
----
docker run -it redhatgov/alpine ps aux
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

.Container processes
[source, bash]
----
PID   USER     TIME   COMMAND
  1   root     0:00   ps aux   <1>
----

<1> The only process we can see is just our last command `ps aux`.

{{% /panel %}}
{{< /panel_group >}}

Containers can share namespaces with other containers. This has to be explicitly set to enable sharing. To enable namespace sharing we will use the `--pid` flag to assign the namespace you want to share.

[source, bash]
----
docker run -it --pid=host redhatgov/alpine ps aux
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

.Host processes
[source, bash]
----
PID   USER     TIME   COMMAND
    1 root       0:05 /usr/lib/systemd/systemd --switched-root --system --deser
    2 root       0:00 [kthreadd]
    4 root       0:00 [kworker/0:0H]
    6 root       0:00 [mm_percpu_wq]
    7 root       0:00 [ksoftirqd/0]
    8 root       0:00 [rcu_sched]
    9 root       0:00 [rcu_bh]
   10 root       0:00 [rcuos/0]
   11 root       0:00 [rcuob/0]
   12 root       0:00 [migration/0]
   13 root       0:00 [watchdog/0]
   14 root       0:00 [cpuhp/0]
   15 root       0:00 [kdevtmpfs]
   16 root       0:00 [netns]
   17 root       0:00 [oom_reaper]
   18 root       0:00 [writeback]
   19 root       0:00 [kcompactd0]
   20 root       0:00 [ksmd]
   21 root       0:00 [crypto]
   22 root       0:00 [kintegrityd]
   23 root       0:00 [bioset]
   24 root       0:00 [kblockd]
   25 root       0:00 [ata_sff]
   26 root       0:00 [md]
   27 root       0:00 [devfreq_wq]
   28 root       0:00 [watchdogd]
   31 root       0:00 [kauditd]
   32 root       0:01 [kswapd0]
   33 root       0:00 [bioset]
   80 root       0:00 [kthrotld]
   81 root       0:00 [acpi_thermal_pm]
   82 root       0:00 [scsi_eh_0]
   83 root       0:00 [scsi_tmf_0]
   84 root       0:00 [scsi_eh_1]
   85 root       0:00 [scsi_tmf_1]
   87 root       0:00 [dm_bufio_cache]
   88 root       0:00 [ipv6_addrconf]
  139 root       0:00 [bioset]
  308 root       0:00 [iscsi_eh]
  311 root       0:00 [rpciod]
  312 root       0:00 [xprtiod]
  416 root       0:00 [kworker/0:1H]
  483 root       0:00 [kdmflush]
  484 root       0:00 [bioset]
  506 root       0:00 [bioset]
  514 root       0:00 [xfsalloc]
  515 root       0:00 [xfs_mru_cache]
  516 root       0:00 [xfs-buf/dm-0]
  519 root       0:00 [xfs-data/dm-0]
  520 root       0:00 [xfs-conv/dm-0]
  521 root       0:00 [xfs-cil/dm-0]
  522 root       0:00 [xfs-reclaim/dm-]
  523 root       0:00 [xfs-log/dm-0]
  524 root       0:00 [xfs-eofblocks/d]
  525 root       0:00 [xfsaild/dm-0]
  603 root       0:02 /usr/lib/systemd/systemd-journald
  619 root       0:00 /usr/lib/systemd/systemd-udevd
  660 root       0:00 [jbd2/sda1-8]
  661 root       0:00 [ext4-rsv-conver]
  670 root       0:00 /sbin/auditd
  688 81         0:03 /usr/bin/dbus-daemon --system --address=systemd: --nofork
  690 994        0:00 /usr/sbin/chronyd
  693 root       0:00 /usr/lib/systemd/systemd-logind
  699 root       0:00 /usr/sbin/gssproxy -D
  709 root       0:00 /usr/sbin/sshd -D
  712 root       0:25 /usr/libexec/docker/docker-containerd-current --listen un
  717 root       0:00 /sbin/agetty --noclear tty1 linux
  733 999        0:00 /usr/lib/polkit-1/polkitd --no-debug
  843 root       0:00 [kdmflush]
  844 root       0:00 [bioset]
  850 root       0:00 [xfs-buf/dm-1]
  851 root       0:00 [xfs-data/dm-1]
  852 root       0:00 [xfs-conv/dm-1]
  853 root       0:00 [xfs-cil/dm-1]
  854 root       0:00 [xfs-reclaim/dm-]
  855 root       0:00 [xfs-log/dm-1]
  856 root       0:00 [xfs-eofblocks/d]
  857 root       0:00 [xfsaild/dm-1]
  935 root       0:45 /usr/bin/dockerd-current --add-runtime oci=/usr/libexec/d
 1079 root       0:00 /usr/libexec/docker/rhel-push-plugin
 1088 1000       0:00 /usr/lib/systemd/systemd --user
 1090 1000       0:00 (sd-pam)
 1989 root       0:03 /usr/sbin/NetworkManager --no-daemon
 2033 root       0:00 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf
 2041 root       0:00 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf
 2974 root       0:00 sshd: vagrant [priv]
 2977 1000       0:00 sshd: vagrant@pts/0
 2978 1000       0:00 -bash
 3101 root       0:00 /usr/lib/systemd/systemd-machined
10917 root       0:00 [kworker/u2:1]
13841 root       0:00 [kworker/0:0]
13979 root       0:00 [kworker/u2:2]
14088 root       0:00 [kworker/0:1]
14210 root       0:00 [kworker/u2:0]
14355 root       0:00 [kworker/0:2]
14379 root       0:00 sudo docker run -it --pid=host bsollar/alpine ps aux
14380 root       0:00 /usr/bin/docker-current run -it --pid=host bsollar/alpine
14396 root       0:00 /usr/libexec/docker/docker-containerd-shim-current 7b5179
14418 root       0:00 ps aux
14427 root       0:00 /usr/libexec/nm-dispatcher
----

As you can see we now have access to all of the processes running on host system by using the `--pid` flag.

{{% /panel %}}
{{< /panel_group >}}


== Network Namespace

Network namespaces provide isolation of network controllers, system resources associated with networking, firewall and routing tables. This allows container to use separate virtual network stack, loopback device and process space. You can add virtual or real devices to the container, assign them their own IP Addresses and even full iptables rules.

Network namespaces create containers with unique IP address and interfaces when containers are launched. Let's run a container and examine the default container network interface.


[source,bash]
----
docker run -it redhatgov/alpine ip addr show
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

.Container network
[source, bash]
----
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000             <1>
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
107: eth0@if108: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP <2>
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link tentative
       valid_lft forever preferred_lft forever
----

<1> Loopback
<2> eth0

{{% /panel %}}
{{< /panel_group >}}

By default a container's network is isolated with it's own IP and interface. By changing the namespace to host by using the `--network` flag, the process will have access to the host machines network interface.

[source,bash]
----
docker run -it --network=host redhatgov/alpine ip addr show
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

.Host network
[source, bash]
----
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000           <1>
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000   <2>
    link/ether 52:54:00:82:00:d4 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 83285sec preferred_lft 83285sec
    inet6 fe80::5054:ff:fe82:d4/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000   <3>
    link/ether 08:00:27:0b:1b:02 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.3/24 brd 172.28.128.255 scope global dynamic eth1
       valid_lft 1196sec preferred_lft 1196sec
    inet6 fe80::a00:27ff:fe0b:1b02/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN       <4>
    link/ether 02:42:07:c4:e0:2d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:7ff:fec4:e02d/64 scope link
       valid_lft forever preferred_lft forever
----

<1> Loopback
<2> eth0
<3> eth1
<4> docker0

*--network=container:NAME_or_ID*: Tells Docker to put this container’s processes inside of the network stack that has already been created inside of another container. The new container’s processes will be confined to their own filesystem and process list and resource limits, but will share the same IP address and port numbers as the first container, and processes on the two containers will be able to connect to each other over the loopback interface.

{{% /panel %}}
{{< /panel_group >}}

{{< alert warning >}}
Note: --network="host" gives the container full access to local system services such as D-bus and is therefore considered insecure.
{{< /alert >}}

=== Sharing Network Namespaces

Containers have a default security model that enforces isolation at the kernel level for process separation as well as network separation between containers. Sometimes you may need to debug a application or container and need to attach or share a containers namespace. Sharing namespaces should only be done in certain situations that require it, but for development it may be appropriate for debugging.

Let's examine how we can share the networking namespace between containers. We will launch a nginx container that will bind to port 80 inside it's container network interface.

[source,bash]
----
docker run -d --name http nginx:alpine
----

Now that we have the Nginx container running in the background as a daemon (-d) we will launch a second container and see if we can use curl to connect to the Nginx container.

[source,bash]
----
sudo docker run --rm redhatgov/fedora curl -s localhost
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

[source, bash]
----
$
----

Should return nothing. Because the namespace is not shared.

{{% /panel %}}
{{< /panel_group >}}

Now let's use the `--network=container:` flag to attach to the `http` containers network interface and try the curl command again.

[source,bash]
----
sudo docker run --rm --network=container:http redhatgov/fedora curl -s localhost
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

[source, html]
----
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>                               <1>
<p>If you see this page, the nginx web server is
successfully installed and working. Further
configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
----

<1> Welcome to nginx! This is the default Nginx message and shows that we were able to share a namespace to connect to this container.

{{% /panel %}}
{{< /panel_group >}}

It can also see and interface with the processes in the shared container.

[source,bash]
----
docker run --pid=container:http alpine ps aux
----

{{< panel_group >}}
{{% panel "Result" %}}

:icons: font

[source,bash]
----
PID   USER     TIME   COMMAND
  1   root     0:00   nginx: master process nginx -g daemon off;  <1>
  5   100      0:00   nginx: worker process                       <2>
  6   root     0:00   ps aux
----

<1> Nginx master process
<2> Nginx worker process


{{% /panel %}}
{{< /panel_group >}}

This is useful for debugging tools, such as strace. This allows you to give more permissions to certain containers without changing or restarting the application.
