---
title: "Exercise 1.5 - Seccomp"
workshops: security_containers
workshop_weight: 70
layout: lab
---


Apply SecComp Profile
Permissions
SecComp defines which system calls should and should not be allowed to be executed by a container. They're defined in a JSON file that is applied when a container starts. In this initial step we've defined seccomp permissions to disable allowing containers to run seccomp.

cat 1_chmod.json

{
    "defaultAction": "SCMP_ACT_ALLOW",
    "architectures": [
        "SCMP_ARCH_X86_64",
        "SCMP_ARCH_X86",
        "SCMP_ARCH_X32"
    ],
    "syscalls": [
        {
            "name": "chmod",
            "action": "SCMP_ACT_ERRNO",
            "args": []
        },
        {
            "name": "chown",
            "action": "SCMP_ACT_ERRNO",
            "args": []
        },
        {
            "name": "chown32",
            "action": "SCMP_ACT_ERRNO",
            "args": []
        }
    ]
}

Applying Restrictions to Containers
Launch a container and try to run chmod.

docker run --rm -it \
  --security-opt seccomp:1_chmod.json \
  benhall/strace \
  chmod 400 /etc/hostname

Because our container attempted to execute chmod, the call failed with Operation not permitted. This is because our seccomp profile blocked it.

We can extend our seccomp profile to list all the calls we want to allow or disallow. This allows us to block potential attack vectors or close vulnerabilities without changing our application.

---------

Identify Syscalls
SecComp is a very low level protocol. In order to block syscalls you first need to identify which calls are being made.

strace is also used to identify the underlying syscall being made by the operating system. While the shell command is called chmod, the underlying system call could be different.

If we take our profile and apply it to Ubuntu, the command will work.

docker run --rm -it \
  --cap-add SYS_PTRACE \
  --security-opt seccomp:1_chmod.json \
  benhall/strace-ubuntu \
  chmod 400 / &&
  echo $?

This is because Ubuntu is using a different syscall under the covers. We need to use strace to update the syscall restrictions but first we need to identify the correct name. The strace commands will output every syscall made by a process. We can use this to identify calls we need to allow / disallow.

Below there are two containers, one based on Ubuntu and one based on Alpine. Run strace and identify which syscalls are being made by each container.

strace on Ubuntu
docker run --rm -it \
  --cap-add SYS_PTRACE \
  --security-opt seccomp:1_chmod.json \
  benhall/strace-ubuntu \
  strace chmod 400 /

When is chmod executed? Is it successful?

strace on Apline
docker run --rm -it \
  --cap-add SYS_PTRACE \
  --security-opt seccomp:1_chmod.json \
  benhall/strace \
  strace chmod 400 /

Why is Alpine different?
