---
title: "Exercise 1.5 - Namespaces"
workshops: security_containers
workshop_weight: 70
layout: lab
---

:icons: font
:imagesdir: /workshops/security_containers/images

= Exercise 1.5 - Namespaces

TODO---------------------


Network Namespace
While cgroups control how much resources a process can use, Namespaces control what a process and see and access.

Example
When containers are launched, a network interface is defined and create. This gives the container a unique IP address and interface.

docker run -it alpine ip addr show

By changing the namespace to host, instead of the container's network being isolated with it's own interface, the process will have access to the host machines network interface.

docker run -it --net=host alpine ip addr show

If the process listens on ports, they'll be listened on the host interface and mapped to the container.



Use Pid Namespace
As with networks, the processes a container can see depends on which namespace it belongs too. By changing the Pid namespace allows a container to interact with processes beyond it's normal scope.

Example
The first container will run in it's own process namespace. As such the only processes it can access are the ones launched in the container.

docker run -it alpine ps aux

By changing the namespace to the host, the container can also see all the other processes running on the system.

docker run -it --pid=host alpine ps aux



Sharing Namespaces
Providing containers access to the host namespace is sometimes required, such as for debugging tooling, but is generally regarded as bad practice. This is because you're breaking out of the container security model which may introduce vulnerabilities. Instead, if it's required, use a shared namespace to provide access to only the namespaces the container requires.

Example
The first container starts an nginx server. This will define a new network and process namespace. The nginx server will bind itself to port 80 of the newly defined network interface.

docker run -d --name http nginx:alpine

Other containers can now reuse this namespace using the syntax container:<name>. Below the curl command can access the HTTP server running on localhost because they share the same network interface.

docker run --net=container:http benhall/curl curl -s localhost

It can also see and interface with the processes in the shared container.

docker run --pid=container:http alpine ps aux

This is useful for debugging tools, such as strace. This allows you to give more permissions to certain containers without changing or restarting the application.
