---
title: Ansible Tower Workshop on Azure
menu:
  main:
    parent: workshops
    pre: fa fa-magic
---

:domain_name: redhatgov.io
:workshop_prefix: workshop
:tower_url: https://{{ workshop_prefix }}-tower0.{{ region }}.cloudapp.azure.com
:ssh_url: https://{{ workshop_prefix }}-tower0.{{ region }}.cloudapp.azure.com/wetty/ssh/azure-user

:icons: font
:iconsdir: http://people.redhat.com/~jduncan/images/icons
:imagesdir: /workshops/ansible_tower/images

= Ansible Tower Workshop on Azure

== Description

Build playbooks to build in security, empower junior staff and offload senior staff, and automate your most tedious tasks!

== What you will learn

- Running ad-hoc commands
- Writing a playbook
- Install and configure Ansible Tower
- Templates and Security.

== Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we’ll get into the lab as soon as possible. That is where we will spend most of our time.
Your Responsibilities
Have a discussion. This will be boring if it’s just us up here talking for over 4 hours.
Participate. We are going to cut you loose with Ansible here in just a little while. Have questions. Have opinions.
Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!

== Labs

{{< labs ansible_tower_azure >}}

{{< importPartial "footer/footer.html" >}}
