---
title: Containers 101 Workshop
menu:
  main:
    parent: workshops
    pre: fa fa-linux
---

:badges:
:icons: font
:imagesdir: /workshops/containers_101/images
:source-highlighter: highlight.js
:source-language: yaml

= Containers 101 Workshop

== Workshop Description

This workshop will introduce you to Linux containers and provide you with foundational container hands-on training.

== Who should attend
Today's container workshop is meant for anyone who has any exposure to Linux containers, whether you have used it or not.

== What you will learn

- How to install docker, buildah, podman, and skopeo
- How to run an existing container image
- How to build a new container from a base container image
- How to push the new container image to a container registry

== Overview

This workshop will start with a short overview about containers and instructions on setting up for the Container 101 Workshop. Next, we will transition into hands-on exercises. We will spend most of our time showing you how to work with container images, Dockerfiles, and container registries.

== Your Responsibilities

Have a discussion. This will be boring if it’s just us talking for over two hours.

Participate, by offering questions and sharing opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy to follow along.

== Exercises

{{< labs containers_101 >}}

{{< importPartial "footer/footer.html" >}}
