---
title: "Exercise 1.4 - Working with a Container Registry"
workshops: containers_101
workshop_weight: 60
layout: lab
---

:badges:
:icons: font
:imagesdir: /workshops/containers_101/images
:source-highlighter: highlight.js
:source-language: yaml


= Exercise 1.4 - Working with a Container Registry

== What it is
A basic container registry is a stateless, highly scalable server side application that stores and  distributes container images.  The docker registry is an open-source project offered under the permissive Apache license.


=== Why use it
You should use a private container registry if you want to:

- tightly control where your images are being stored
- fully own your images distribution pipeline
- integrate image storage and distribution tightly into your in-house development workflow

First, lets install the `docker-distribution` package, to provide the registry software:

.Install Registry
[source, bash]
----
yum install -y docker-distribution
----


Next, lets set the service to auto-start at system boot:

.Enable the Docker Container Registry
[source, bash]
----
systemctl enable docker-distribution
----


The container registry configuration file will need to be modified to allow the use of https (secure) communications.  First, we will generate a certificate.

.Generate https Certificate
[source, bash]
----
mkdir /etc/docker-distribution/certs
cd /etc/docker-distribution/certs
openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 365 -out domain.crt
----


Answer the questions that OpenSSL asks, in any way that you see fit, but make sure that you specify a `Common Name` of `localhost`.  Here is an example:

.Enter certificate data
[source, bash]
----
Generating a 4096 bit RSA private key
............................................................++
...............................................................++
writing new private key to 'domain.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:US
State or Province Name (full name) []:Maryland
Locality Name (eg, city) [Default City]:Middletown
Organization Name (eg, company) [Default Company Ltd]:Red Hat
Organizational Unit Name (eg, section) []:BD SA Team
Common Name (eg, your name or your server's hostname) []:localhost
Email Address []:alexander@redhat.com
----

To finish this configuration, let's add the cert to the system's trusted database:

.Trust a Self-Generated Certificate
[source, bash]
----
cp domain.crt /etc/pki/tls/certs
update-ca-trust extract
----


Next, we will add secure mode to the container registry configuration.  Edit the file '/etc/docker-distribution/registry/config.yml' so that it looks like the following:

.Edit Registry Configuration File
[source, bash]
----
cat /etc/docker-distribution/registry/config.yml

version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
    delete:
        enabled: true
http:
    addr: :5000
    tls:
      certificate: /etc/docker-distribution/certs/domain.crt
      key: /etc/docker-distribution/certs/domain.key
    host: https://localhost:5000
    relativeurls: false
----


Next, we can start the registry:

.Start the registry
[source, bash]
----
systemctl start docker-distribution
----


Before we upload anything, let's take a look to see what images we have in the local image database:

.View Current Images
[source, bash]
----
podman images

REPOSITORY                        TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
fedora_postgresql                 latest              93e0fb06be2b        7 minutes ago       407.3 MB
docker.io/fedora                  latest              c7d2f0130dae        8 days ago          204.3 MB
registry.access.redhat.com/rhel   latest              c4f590bbcbe3        12 days ago         158.2 MB
----


Now, we will push the container to the local registry.  Either of these two commands will work, showing that there is always more than one way to skin a cat.

.Push fedora_postgresql via buildah
[source, bash]
----
buildah push fedora_postgresql:latest localhost:5000/fedora_postgresql:latest
----

.Push fedora_postgresql via skopeo
[source, bash]
----
skopeo copy containers-storage:fedora_postgresql:latest docker://localhost:5000/fedora_postgresql:latest
----


Next, let's search the registry to make sure that our image made it, and is available:

.Search for a Container Image in the Local Registry
[source, bash]
----
podman search --registry localhost:5000 postgresql

INDEX            NAME                               DESCRIPTION   STARS   OFFICIAL   AUTOMATED
localhost:5000   localhost:5000/fedora_postgresql
----

