---
title: "Exercise 1.0 - Install docker, buildah, skopeo, and podman"
workshops: containers_101
workshop_weight: 20
layout: lab
---

:badges:
:icons: font
:imagesdir: /workshops/containers_101/images
:source-highlighter: highlight.js
:source-language: yaml

= Exercise 1.0 - Install buildah, skopeo, and podman

== Install buildah, skopeo, and podman

The docker tooling requires a daemon (service) to operate.  There are alternative CLI tools which provide focused separation of the docker command's features and extend their capabilities.  The following three commands will be used throughout this workshop.

- Buildah - used to build Open Container Initiative (OCI) format or docker format container images without the need for a daemon.
- Podman - provides the ability to directly run container images without a daemon.  Podman can pull container images from a container registry if they are not available locally
- Skopeo -  offers features for pulling and pushing containers to registries.  Moving containers between registries is supported.  Container image inspection is also offered and some introspective capabilities can be performed without first downloading the container itself.

[source, bash]
----
yum -y install buildah skopeo podman
----
