# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "fiercesw"
license = "MIT"
licenselink = "https://github.com/FierceSoftware/redhatgov.github.io/blob/master/themes/fiercesw/LICENSE.md"
description = "The Fierce Software stylized theme for the Red Hat Gov workshop Hugo site"
homepage = "http://workshops.fiercesw.network/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Ken Moini"
  homepage = "https://www.kenmoini.com"

# If porting an existing theme
[original]
  name = "redhatgov"
  homepage = "http://redhatgov.github.io/"
  repo = "https://github.com/RedHatGov/redhatgov.github.io/"
